name: Daily Job Email

on:
  schedule:
    - cron: "30 4 * * *"   # Every day at 10:00 AM IST
  workflow_dispatch:        # Allow manual run too

# jobs:
#   send-daily-email:
#     runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      # - name: Run email script
      #   env:
      #     EMAIL_USER: ${{ secrets.EMAIL_USER }}
      #     EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python main.py
